# Generated by Django 3.2.6 on 2021-08-09 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0002_customuser_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length='1200', verbose_name='Post text')),
                ('post_dt', models.DateField(auto_now=True, verbose_name='Post created time')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_app.customuser', verbose_name='Author')),
            ],
        ),
    ]
